medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', '127.0.0.1') }}"
      port: "{{ env_var('DB_PORT', '5433') | int }}"
      user: "{{ env_var('DB_USER', 'med_user') }}"
      password: "{{ env_var('DB_PASSWORD', 'med_password') }}"
      dbname: "{{ env_var('DB_NAME', 'med_warehouse') }}"
      schema: analytics
      threads: 4
